### ISSUE TITLE
[Installer] [MySQL] Syntax error

### ISSUE THREAD

**Issue by Morketh** [CollectiveIndustries/StarfleetDelta#17]
ERROR 1064 (42000) at line 18: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-
DROP DATABASE IF EXISTS `ufgq`' at line 1

**Comment by Morketh** [comment]
as a result using the installer does not install a fresh a copy of the database and you end up with this error.
```Traceback (most recent call last):
  File "./installer.py", line 59, in <module>
    cursor.execute(sql,(username,password) )
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.IntegrityError: (1062, "Duplicate entry 'admin' for key 'uname_uniq'")

```
```
