### ISSUE TITLE
[Installer] Programming Error on accounts table

### ISSUE THREAD

**Issue by Morketh** [CollectiveIndustries/StarfleetDelta#22]
```
ERROR 1067 (42000) at line 22: Invalid default value for 'JoinDate'
```
Check default values for JoinDate.
this might be causing the following error messages:
```
Traceback (most recent call last):
  File "./installer.py", line 59, in <module>
    cursor.execute(sql,(username,password) )
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
_mysql_exceptions.ProgrammingError: (1146, "Table 'ufgq.accounts' doesn't exist")
```
I dont think Python is able to upload the data correctly and so nothing gets pushed to the Database.

**Comment by Morketh** [comment]
Apparently its STILL not fixed
```
ERROR 1293 (HY000) at line 22: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```

**Comment by Morketh** [comment]
I think the best way to go with this is build a promotions table.
+ Would record promotion history
+ Would link the account ID with the promotion information.

Account table will need to retain the profile basics
+ User, ID, UUID, password for starfleetdelta.com services, etc.

**Comment by Morketh** [comment]
Apparently its STILL not fixed
```
ERROR 1293 (HY000) at line 22: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
```
