### ISSUE TITLE
[Installer] mysqlConfigFile Error

### ISSUE THREAD

**Issue by hammerzaine** [CollectiveIndustries/StarfleetDelta#3]
```
Traceback (most recent call last):
  File "./installer.py", line 18, in <module>
    from module import config, functions
  File "/root/SOURCE/UFGQ/python/module/config.py", line 47, in <module>
    _IN_MYSQL_FILE_ = ConfigSectionMap("DB")['mysqlConfigFile']
KeyError: 'mysqlConfigFile'
```

File doesn't like mysqlConfigFile. changed it to file and it worked. need to find a variable that the group and program can agree on

**Comment by Morketh** [comment]
See Issue #2

**Comment by Morketh** [comment]
Fixed
